subscribers:

  camera_reading:
    topic: /ros_indigosdk_node/stitched_image0
    queue_size: 1

actions:

  camera_reading:
    name: /omni_darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /omni_darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /omni_yolo_bboxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /omni_darknet_ros/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: false
  wait_key_delay: 1
  enable_console_output: false
